### ISSUE TITLE
error

### ISSUE THREAD

**Issue by carlos837** [Terax235/fnbot-client#10]
[EGL] Logging in...
Authenticating...
Authentification successful (2.40s)
XMPP-Client connecting...
XMPP-Client successfully connected (1.56s)
[EGL] Logged in as [PRIVATE] (ID: [PRIVATE]).
(node:32920) UnhandledPromiseRejectionWarning: TypeError: JSON.beautify is not a function
    at Object.exports.init (C:\Users\[PRIVATE]\Desktop\fnbot-client\structures\Fortnite.js:91:59)
    at async C:\Users\[PRIVATE]\Desktop\fnbot-client\index_nogui.js:38:16
(node:32920) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:32920) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by wavy0** [comment]
The function doesn't exist, hmmmm.

**Comment by Terax235** [comment]
That should not happen, the function is defined within [index.js](https://github.com/Terax235/fnbot-client/blob/master/index.js#L12). I'm not sure whether I will look into that, since I really don't have time for the project atm.
