### ISSUE TITLE
Error: [Account Authorization] Cannot get exchange code! on release "Version 1.2.1"

### ISSUE THREAD

**Issue by Skadro** [Terax235/fnbot-client#3]
Output:
```
[2] Logging in...
[i] Using no GUI login
(node:8704) UnhandledPromiseRejectionWarning: Error: [Account Authorization] Cannot get exchange code!
    at AccountAuth.auth (C:\snapshot\fnbot-client\node_modules\epicgames-client\src\Account\Auth.js:171:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Account.authorize (C:\snapshot\fnbot-client\node_modules\epicgames-client\src\Account\index.js:56:14)
    at async Launcher.login (C:\snapshot\fnbot-client\node_modules\epicgames-client\src\Client\index.js:263:18)
    at async C:\snapshot\fnbot-client\structures\Fortnite.js:39:23
(node:8704) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8704) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Config:
```
{
    "bot": {
        "login": {
            "email": "***",
            "password": "***"
        },
        "party_privacy": "public",
        "autoSitOut": false,
        "acceptallfriends": true,
        "owner": "***"
    },
    "server_url": "https://fnapi.terax235.com",
    "preferred_language": "en",
    "build": {
        "fortnite": {
            "buildID": "1:1:13617966",
            "netCL": "13617966",
            "build": "++Fortnite+Release-13.20-CL-13777676",
            "engineBuild": "4.26.0-13777557+++Fortnite+Release-13.20",
            "UserAgent": "Fortnite/++Fortnite+Release-13.20-CL-13777676 Windows/10.0.17134.1.768.64bit"
        },
        "launcher": {
            "build": "10.17.2-13709133+++Portal+Release-Live",
            "engineVersion": "4.23.0-13709133+++Portal+Release-Live",
            "netCL": "13709133"
        }
    }
}
```

**Comment by YungSamzy** [comment]
same, any fix? DM me on discord at Samzy#0174 if you can fix it! thx

**Comment by Terax235** [comment]
If using the source code, updating the packages with `npm update` should resolve the issue.

**Comment by Terax235** [comment]
Also, the no GUI login is not working all the time because of Epic Games adding captcha requirements or other ways to prevent unauthorized logins.

**Comment by Terax235** [comment]
The latest release fixed this issue since I'm now using fnbr.js.
